# Generated by Django 3.1.4 on 2021-07-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_Name', models.JSONField()),
                ('t_sex', models.JSONField()),
                ('t_work', models.JSONField()),
                ('t_education', models.JSONField()),
                ('t_level', models.JSONField()),
                ('t_title', models.JSONField()),
                ('t_ID_card', models.JSONField()),
                ('t_age', models.JSONField()),
                ('t_from', models.JSONField()),
                ('t_province', models.JSONField()),
                ('t_school', models.JSONField()),
                ('t_introduction', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_education', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fromWhere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_from', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='identity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_province', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_school', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_sex', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_Name', models.CharField(max_length=20)),
                ('t_sex', models.CharField(max_length=2)),
                ('t_work', models.CharField(max_length=200)),
                ('t_education', models.CharField(max_length=20)),
                ('t_level', models.CharField(max_length=20)),
                ('t_title', models.CharField(max_length=20)),
                ('t_ID_card', models.CharField(max_length=50)),
                ('t_age', models.IntegerField()),
                ('t_from', models.CharField(max_length=30)),
                ('t_province', models.CharField(max_length=20)),
                ('t_school', models.CharField(max_length=20)),
                ('t_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='courseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_type', models.CharField(max_length=20)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allTeachers.teachermodel')),
            ],
        ),
    ]
