# Generated by Django 3.1.4 on 2021-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTeachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseCategoryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_category', models.CharField(max_length=100)),
                ('c_month', models.CharField(max_length=200)),
                ('c_cycle', models.CharField(max_length=20)),
                ('c_people', models.CharField(max_length=20)),
                ('c_year', models.CharField(max_length=20)),
            ],
        ),
    ]
